from enum import Enum

class Status(Enum):
    LOADING = "LOADING"
    PRELIM_SUCCESS = "PRELIM_SUCCESS"
    COMPLETE_SUCCESS = "COMPLETE_SUCCESS"
    COMPLETE_FAIL = "COMPLETE_FAIL"
    RECEIVED_REQUEST = "RECEIVED_REQUEST"